
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver  #요기는 마리아디비 고유값#
        url: jdbc:mariadb://localhost:3306/mariadb #마리아디비고유값 뒤에는 내 db명#
        username: mariadb #하이디 아이디 비번#
        password: mariadb #하이디 아이디 비번#